# Generated by Django 4.0.2 on 2022-03-03 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greencollect_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycollect',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitycollect',
            name='startDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitycollect',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
