# Generated by Django 4.0.2 on 2022-03-08 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencollect_api', '0002_communitycollect_creationdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='collect',
        ),
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='point',
            name='wastes',
            field=models.ManyToManyField(related_name='wastes_for_point', to='greencollect_api.Waste'),
        ),
    ]
