# Generated by Django 4.0.2 on 2022-03-08 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencollect_api', '0003_remove_point_collect_point_latitude_point_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycollect',
            name='latitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='communitycollect',
            name='longitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
