# Generated by Django 4.0.2 on 2022-03-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencollect_api', '0004_communitycollect_latitude_communitycollect_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitycollect',
            name='collectPoint',
        ),
        migrations.AddField(
            model_name='communitycollect',
            name='wastes',
            field=models.ManyToManyField(related_name='wastes_for_community_collect', to='greencollect_api.Waste'),
        ),
    ]
