# Generated by Django 4.0.2 on 2022-03-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greencollect_api', '0005_remove_communitycollect_collectpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitycollect',
            name='startDate',
        ),
    ]
