# Generated by Django 4.0.2 on 2022-03-14 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greencollect_api', '0008_alter_point_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
