name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r env/requirements.txt
    - name: Run tests
      run: |
        . venv/bin/activate
        python manage.py test
    - name: Check for deployment
      run: |
        . venv/bin/activate
        python manage.py check --deploy
    - name: Deployment of the app