name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    # Step 2: create virtual env and install dependencies
    - name: Install dependencies
      command: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
    # Step 3: run linter and tests
    - name: run tests
      command: |
        . venv/bin/activate
        flake8 --exclude=venv* --statistics
        pytest -v --cov=calculator